url: 'https://haervig.com'

permalink: pretty
title: Jakob Hærvig
cv: 'https://cv.haervig.com'
logo: /assets/img/portrait.png
description: Associate Professor at AAU
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
  owner_url: 'https://github.com/jakobhaervig'