url: 'https://haervig.com'

permalink: pretty
title: Jakob Hærvig
cv: 'https://cv.haervig.com'
logo: /assets/img/portrait.jpg
description: "Research group leader for Multiphase Flows and Heat Transfer"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
  owner_url: 'https://github.com/jakobhaervig'