# main text of home
title: Jakob Hærvig
bio: Associate Professor

description: 

# if it's an external image, update below for true
# better with square images
external-image: true
picture: https://avatars.githubusercontent.com/u/10219471

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://cv.haervig.com

url: https://haervig.com

permalink: /:title/

linkedin: jakobhaervig
github: jakobhaervig
email: jakob.haervig@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal


# if you don't need "about" or "blog", comment them out below
about: true
#blog: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
